// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseInstaller():Promise<void>;

export function GetInstallDir():Promise<string>;

export function GetReleases():Promise<Array<{tag: string, prerelease: boolean}>>;

export function Install(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function LaunchAndClose():Promise<void>;
