// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseInstaller() {
  return window['go']['main']['App']['CloseInstaller']();
}

export function GetChannel() {
  return window['go']['main']['App']['GetChannel']();
}

export function GetInstallDir() {
  return window['go']['main']['App']['GetInstallDir']();
}

export function GetReleases() {
  return window['go']['main']['App']['GetReleases']();
}

export function Install(arg1, arg2, arg3) {
  return window['go']['main']['App']['Install'](arg1, arg2, arg3);
}

export function LaunchAndClose() {
  return window['go']['main']['App']['LaunchAndClose']();
}

export function Ready() {
  return window['go']['main']['App']['Ready']();
}
