// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateTerminal(arg1, arg2) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2);
}

export function CtrlClickPath(arg1, arg2) {
  return window['go']['main']['App']['CtrlClickPath'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExplorerCreateDir(arg1) {
  return window['go']['main']['App']['ExplorerCreateDir'](arg1);
}

export function ExplorerCreateFile(arg1) {
  return window['go']['main']['App']['ExplorerCreateFile'](arg1);
}

export function ExplorerDelete(arg1) {
  return window['go']['main']['App']['ExplorerDelete'](arg1);
}

export function ExplorerGetFile(arg1) {
  return window['go']['main']['App']['ExplorerGetFile'](arg1);
}

export function ExecSilent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecSilent'](arg1, arg2, arg3);
}

export function ExplorerGetTree() {
  return window['go']['main']['App']['ExplorerGetTree']();
}

export function ExplorerMove(arg1, arg2) {
  return window['go']['main']['App']['ExplorerMove'](arg1, arg2);
}

export function ExplorerOpen(arg1) {
  return window['go']['main']['App']['ExplorerOpen'](arg1);
}

export function ExplorerRename(arg1, arg2) {
  return window['go']['main']['App']['ExplorerRename'](arg1, arg2);
}

export function ExplorerReveal(arg1) {
  return window['go']['main']['App']['ExplorerReveal'](arg1);
}

export function ExplorerSaveFile(arg1, arg2) {
  return window['go']['main']['App']['ExplorerSaveFile'](arg1, arg2);
}

export function FetchExternalPlugin(arg1) {
  return window['go']['main']['App']['FetchExternalPlugin'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetCompletions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCompletions'](arg1, arg2, arg3);
}

export function GetFileLanguage(arg1) {
  return window['go']['main']['App']['GetFileLanguage'](arg1);
}

export function GetSystemPerf() {
  return window['go']['main']['App']['GetSystemPerf']();
}

export function GetSystemPorts() {
  return window['go']['main']['App']['GetSystemPorts']();
}

export function GetTerminalCwd(arg1) {
  return window['go']['main']['App']['GetTerminalCwd'](arg1);
}

export function InterruptCommand(arg1) {
  return window['go']['main']['App']['InterruptCommand'](arg1);
}

export function KillPort(arg1) {
  return window['go']['main']['App']['KillPort'](arg1);
}

export function LoadSession() {
  return window['go']['main']['App']['LoadSession']();
}

export function OpenNewWindow() {
  return window['go']['main']['App']['OpenNewWindow']();
}

export function PerformUpdate(arg1) {
  return window['go']['main']['App']['PerformUpdate'](arg1);
}

export function ReadDatabase(arg1) {
  return window['go']['main']['App']['ReadDatabase'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveCustomTheme(arg1) {
  return window['go']['main']['App']['SaveCustomTheme'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function ScanProblems(arg1) {
  return window['go']['main']['App']['ScanProblems'](arg1);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetClipboardText(arg1) {
  return window['go']['main']['App']['SetClipboardText'](arg1);
}

export function SetTerminalCwd(arg1, arg2) {
  return window['go']['main']['App']['SetTerminalCwd'](arg1, arg2);
}

export function StartPerfMonitor(arg1) {
  return window['go']['main']['App']['StartPerfMonitor'](arg1);
}

export function StopPerfMonitor(arg1) {
  return window['go']['main']['App']['StopPerfMonitor'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
