// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fullscreen} from '../models';
import {main} from '../models';
import {plugins} from '../models';
import {config} from '../models';
import {perf} from '../models';
import {ports} from '../models';
import {session} from '../models';
import {database} from '../models';
import {problems} from '../models';
import {search} from '../models';

export function CheckForUpdate():Promise<string>;

export function ExecSilent(arg1:string,arg2:string,arg3:string[]):Promise<string>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateTerminal(arg1:string,arg2:string):Promise<void>;

export function CtrlClickPath(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<void>;

export function ExplorerCreateDir(arg1:string):Promise<void>;

export function ExplorerCreateFile(arg1:string):Promise<void>;

export function ExplorerDelete(arg1:string):Promise<void>;

export function ExplorerGetFile(arg1:string):Promise<string>;

export function ExplorerGetTree():Promise<fullscreen.FileNode>;

export function ExplorerMove(arg1:string,arg2:string):Promise<void>;

export function ExplorerOpen(arg1:string):Promise<fullscreen.FileNode>;

export function ExplorerRename(arg1:string,arg2:string):Promise<void>;

export function ExplorerReveal(arg1:string):Promise<void>;

export function ExplorerSaveFile(arg1:string,arg2:string):Promise<void>;

export function FetchExternalPlugin(arg1:string):Promise<plugins.ExternalPluginInfo>;

export function GetAppConfig():Promise<config.Config>;

export function GetClipboardText():Promise<string>;

export function GetCompletions(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetFileLanguage(arg1:string):Promise<string>;

export function GetSystemPerf():Promise<perf.PerfData>;

export function GetSystemPorts():Promise<Array<ports.PortInfo>>;

export function GetTerminalCwd(arg1:string):Promise<string>;

export function InterruptCommand(arg1:string):Promise<void>;

export function KillPort(arg1:string):Promise<string>;

export function LoadSession():Promise<Array<session.Tab>>;

export function OpenNewWindow():Promise<void>;

export function PerformUpdate(arg1:string):Promise<void>;

export function ReadDatabase(arg1:string):Promise<database.DBSchema>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveAppConfig(arg1:config.Config):Promise<void>;

export function SaveCustomTheme(arg1:Record<string, string>):Promise<void>;

export function SaveSession(arg1:Array<session.Tab>):Promise<void>;

export function ScanProblems(arg1:string):Promise<problems.ProbResult>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<search.Result>>;

export function SelectDirectory():Promise<string>;

export function SetClipboardText(arg1:string):Promise<void>;

export function SetTerminalCwd(arg1:string,arg2:string):Promise<void>;

export function StartPerfMonitor(arg1:string):Promise<void>;

export function StopPerfMonitor(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
