// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateTerminal(arg1) {
  return window['go']['main']['App']['CreateTerminal'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetCompletions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCompletions'](arg1, arg2, arg3);
}

export function GetFileLanguage(arg1) {
  return window['go']['main']['App']['GetFileLanguage'](arg1);
}

export function GetTerminalCwd(arg1) {
  return window['go']['main']['App']['GetTerminalCwd'](arg1);
}

export function InterruptCommand(arg1) {
  return window['go']['main']['App']['InterruptCommand'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetTerminalCwd(arg1, arg2) {
  return window['go']['main']['App']['SetTerminalCwd'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
