// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateTerminal(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<void>;

export function GetAppConfig():Promise<main.Config>;

export function GetClipboardText():Promise<string>;

export function GetCompletions(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetFileLanguage(arg1:string):Promise<string>;

export function GetTerminalCwd(arg1:string):Promise<string>;

export function InterruptCommand(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SetTerminalCwd(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
